config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :subjects
  resources :animals

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#home'

  resources :forum_threads do
    resources :forum_posts, module: :forum_threads
  end
end

app/models/forum_post.rb
# == Schema Information
#
# Table name: forum_posts
#
#  id              :integer          not null, primary key
#  body            :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  forum_thread_id :integer
#  user_id         :integer
#
class ForumPost < ApplicationRecord
  belongs_to :user
  belongs_to :forum_thread
end

app/controllers/forum_threads/forum_posts_controller.rb
class ForumThreads::ForumPostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_forum_thread

  def create
    @forum_post = @forum_thread.forum_posts.new forum_post_params
    @forum_post.user = current_user

    if @forum_post.save
      redirect_to forum_thread_path(@forum_thread, anchor: "forum_post_#{forum_post.id}", notice: "Successfully posted!")
    else
      redirect_to @forum_thread, notice: "Unable to save your post"
    end
  end

  private

  def set_forum_thread
    @forum_thread ||= ForumThread.find(params[:forum_thread_id])
  end

  def forum_post_params
    params.require(:forum_post).permit(:body)
  end
end

app/helpers/forum_posts_helper.rb
module ForumPostsHelper
end

app/views/forum_posts/_form.html.erb
<%= form_with(model: forum_post, local: true) do |form| %>
  <% if forum_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(forum_post.errors.count, "error") %> prohibited this forum_post from being saved:</h2>

      <ul>
        <% forum_post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :forum_thread_id %>
    <%= form.number_field :forum_thread_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/forum_posts/edit.html.erb
<h1>Editing Forum Post</h1>

<%= render 'form', forum_post: @forum_post %>

<%= link_to 'Show', @forum_post %> |
<%= link_to 'Back', forum_posts_path %>

app/views/forum_posts/index.html.erb
<h1>Forum Posts</h1>

<table>
  <thead>
    <tr>
      <th>Forum thread</th>
      <th>User</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forum_posts.each do |forum_post| %>
      <tr>
        <td><%= forum_post.forum_thread_id %></td>
        <td><%= forum_post.user_id %></td>
        <td><%= forum_post.body %></td>
        <td><%= link_to 'Show', forum_post %></td>
        <td><%= link_to 'Edit', edit_forum_post_path(forum_post) %></td>
        <td><%= link_to 'Destroy', forum_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forum Post', new_forum_post_path %>

app/views/forum_posts/new.html.erb
<h1>New Forum Post</h1>

<%= render 'form', forum_post: @forum_post %>

<%= link_to 'Back', forum_posts_path %>

app/views/forum_posts/show.html.erb
<p>
  <strong>Forum thread:</strong>
  <%= @forum_post.forum_thread_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @forum_post.user_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @forum_post.body %>
</p>

<%= link_to 'Edit', edit_forum_post_path(@forum_post) %> |
<%= link_to 'Back', forum_posts_path %>