config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :subjects
  resources :animals

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#home'

  resources :forum_threads do
    resources :forum_posts, module: :forum_threads
  end
end

app/models/forum_thread.rb
# == Schema Information
#
# Table name: forum_threads
#
#  id         :integer          not null, primary key
#  subject    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
class ForumThread < ApplicationRecord
  has_many :forum_posts, dependent: :delete_all
  belongs_to :user

  accepts_nested_attributes_for :forum_posts

  validates :subject, presence: true
  validates_associated :forum_posts
end

app/controllers/forum_threads/forum_posts_controller.rb
class ForumThreads::ForumPostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_forum_thread

  def create
    @forum_post = @forum_thread.forum_posts.new forum_post_params
    @forum_post.user = current_user

    if @forum_post.save
      redirect_to forum_thread_path(@forum_thread, anchor: "forum_post_#{forum_post.id}", notice: "Successfully posted!")
    else
      redirect_to @forum_thread, notice: "Unable to save your post"
    end
  end

  private

  def set_forum_thread
    @forum_thread ||= ForumThread.find(params[:forum_thread_id])
  end

  def forum_post_params
    params.require(:forum_post).permit(:body)
  end
end

app/controllers/forum_threads_controller.rb
require 'byebug'

class ForumThreadsController < ApplicationController
  before_action :authenticate_user!, except: %i(index show)
  before_action :set_forum_thread, except: %i(index new create)

  def index
    @forum_threads = ForumThread.all
  end

  def show
  end

  def new
    @forum_thread = ForumThread.new
    @forum_thread.forum_posts.new
  end

  def create
    @forum_thread = current_user.forum_threads.new forum_thread_params
    @forum_thread.forum_posts.first.user_id = current_user.id

    if @forum_thread.save
      redirect_to @forum_thread
    else
      render action: :new
    end
  end

  def update
    @forum_thread.update(forum_thread_params)

    render action: :show
  end

  private

  def set_forum_thread
    @forum_thread = ForumThread.find(params[:id])
  end

  def forum_thread_params
    params.require(:forum_thread).permit(:subject, forum_posts_attributes: %i(id body))
  end
end

app/helpers/forum_threads_helper.rb
module ForumThreadsHelper
end

app/views/forum_threads/_form.html.erb
<%= form_for @forum_thread, local: true, class: "form" do |form| %>
  <% if @forum_thread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum_thread.errors.count, "error") %> prohibited this forum_thread from being saved:</h2>

      <ul>
        <% @forum_thread.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :subject, placeholder: "Subject", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.fields_for :forum_posts do |post| %>
      <%= post.text_area :body, placeholder: "Body", rows: 10, class: "form-control mt-3" %>
    <% end %>
  </div>

  <div class="actions mt-3 mb-2">
    <%= form.submit "Submit", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/forum_threads/edit.html.erb
<h1>Editing Forum Thread</h1>

<%= render 'form', forum_thread: @forum_thread %>

<%= link_to 'Show', @forum_thread %> |
<%= link_to 'Back', forum_threads_path %>

app/views/forum_threads/index.html.erb
<h1>Forum Threads</h1>

<table>
  <tbody>
    <% unless @forum_threads.present? %>
      No threads were found.
    <% end %>
    <% @forum_threads.each do |thread| %>
      <tr>
        <td><%= link_to thread.subject, thread, class: "text-decoration-none headline" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thread', new_forum_thread_path %>

app/views/forum_threads/new.html.erb
<h1>New Thread</h1>

<%= render 'form', forum_thread: @forum_thread %>

<%= link_to 'Back', forum_threads_path %>

app/views/forum_threads/show.html.erb
<div class="headline border-gray">
  <h1><%= @forum_thread.subject %></h1>
</div>

<p>
  <%= @forum_thread.forum_posts.each do |post| %>
  <% end %>
</p>

<%= link_to 'Edit', edit_forum_thread_path(@forum_thread) %> |
<%= link_to 'Back', forum_threads_path %>